name: detekt

on:
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      # arrange
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: reviewdog/action-setup@v1
      # act
      - run: ./gradlew detekt --stacktrace
      # assert
      - name: Run reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./app/build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"
